<?php

// ------------------------------------------------
// Error Codes
  $errCode = Array();
  $errCode['N/A'] = "Ikke HTTP";
  $errCode[OK]    = "Valid hostname";
  $errCode[FEJL]  = "Invalid hostname";
  $errCode[Død]   = "No response";
  $errCode[100]   = "Continue";
  $errCode[101]   = "Switching Protocols";
  $errCode[200]   = "OK";
  $errCode[201]   = "Created";
  $errCode[202]   = "Accepted";
  $errCode[203]   = "Non-Authoritative Information";
  $errCode[204]   = "No Content";
  $errCode[205]   = "Reset Content";
  $errCode[206]   = "Partial Content";
  $errCode[300]   = "Multiple Choices";
  $errCode[301]   = "Moved Permanently";
  $errCode[302]   = "Found";
  $errCode[303]   = "See Other";
  $errCode[304]   = "Not Modified";
  $errCode[305]   = "Use Proxy";
  $errCode[307]   = "Temporary Redirect";
  $errCode[400]   = "Bad Request";
  $errCode[401]   = "Unauthorized";
  $errCode[402]   = "Payment Required";
  $errCode[403]   = "Forbidden";
  $errCode[404]   = "Not Found";
  $errCode[405]   = "Method Not Allowed";
  $errCode[406]   = "Not Acceptable";
  $errCode[407]   = "Proxy Authentication Required";
  $errCode[408]   = "Request Timeout";
  $errCode[409]   = "Conflict";
  $errCode[410]   = "Gone";
  $errCode[411]   = "Length Required";
  $errCode[412]   = "Precondition Failed";
  $errCode[413]   = "Request Entity Too Large";
  $errCode[414]   = "Request-URI Too Long";
  $errCode[415]   = "Unsupported Media Type";
  $errCode[416]   = "Requested Range Not Satisfiable";
  $errCode[417]   = "Expectation Failed";
  $errCode[500]   = "Internal Server Error";
  $errCode[501]   = "Not Implemented";
  $errCode[502]   = "Bad Gateway";
  $errCode[503]   = "Service Unavailable";
  $errCode[504]   = "Gateway Timeout";
  $errCode[505]   = "HTTP Version Not Supported";

